# Generated by Django 5.0.14 on 2026-08-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested (Payment Held)"),
                    ("CONFIRMED", "Confirmed"),
                    ("CHECKED_IN", "Checked In"),
                    ("STAYED", "Stayed (Completed)"),
                    ("CANCELLED_REFUNDED", "Cancelled & Refunded"),
                    ("CANCELLED", "Cancelled"),
                    ("REJECTED", "Rejected"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("PAYMENT_PENDING", "Payment Pending"),
                    ("COMPLETED", "Completed"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
    ]
