# Generated by Django 5.0.14 on 2026-08-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="estimated_arrival_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="purpose_of_visit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
