# Generated by Django 5.0.14 on 2026-08-06 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingavailability",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="listingphoto",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="pol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="listings.polsector",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="listingavailability",
            unique_together={("listing", "date")},
        ),
    ]
