# Generated by Django 5.0.14 on 2026-08-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("under_review", "Under Review"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
