# Generated by Django 5.0.14 on 2026-08-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_listing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="property_document_type",
            field=models.CharField(
                default="Rental Agreement / Tax Receipt", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="property_document_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
