# Generated by Django 5.0.14 on 2026-08-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_id_document_url_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("VERIFIED", "Verified"),
                    ("PENDING_VERIFICATION", "Pending Verification"),
                    ("REVERIFICATION_REQUIRED", "Re-verification Required"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING_VERIFICATION",
                max_length=30,
            ),
        ),
    ]
