# Generated by Django 5.0.14 on 2026-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_verification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="resubmitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
