# Generated by Django 5.0.14 on 2026-08-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_resubmitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
